#default applications properties for AWS environment
server:
  port: 5000

bvb:
  resources:
    starting-page: https://www.bvb.ro/FinancialInstruments/SelectedData/CurrentReports

mail:
  from: bvbeventnotifier@gmail.com
  to: popescumariusvasile@gmail.com
  password: csvfirqbyneafdds

folders:
  download: /temp/raw_reports

spring:
  liquibase:
    enabled: true
    change-log: classpath:liquibase/changelog-master.xml
  jpa:
    open-in-view: false

logging:
  level:
    liquibase: INFO