server:
  port: 8080
#swagger added on: http://localhost:8080/swagger-ui/#/
folders:
  download: temp/raw_reports

logging:
  level:
    com:
      scopert:
        bvbeventnotifier:
          scheduler: DEBUG
          crawler:
            CurrentReportsCrawler: DEBUG