#default applications properties for AWS environment
server:
  port: 5000

bvb:
  resources:
    starting-page: https://www.bvb.ro/FinancialInstruments/SelectedData/CurrentReports

mail:
  from: bvbeventnotifier@gmail.com
  to: popescumariusvasile@gmail.com
  password: csvfirqbyneafdds
  enabled: true

folders:
  download: /temp/raw_reports

spring:
  datasource:
    url: jdbc:h2:~/bvbevents;AUTO_SERVER=TRUE;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;
    username: bvb
    password: bvb
    driverClassName: org.h2.Driver
  liquibase:
    enabled: true
    change-log: classpath:liquibase/changelog-master.xml
  h2:
    console:
      enabled: true

logging:
  level:
    liquibase: INFO